application:
  title: @project.name@
  version: @project.version@
  author: Darwin

spring:
  security:
    oauth2:
      client:
        provider:
          external:
            issuer-uri: http://localhost:8080/realms/external

        registration:
          external:
            provider: external
            client-name: external-client
            client-id: external-client
            client-secret: xWhpydqVQnp5kSnyFuMeoU4X1hnseo4k
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code